
let do_not_accept_tez : string = "Do not accept Tez"
let owner_already_exist : string = "Owner already exists"
let wrong_state : string = "Wrong state"
let not_parent : string = "Not parent"
let not_owner : string = "Not owner"
let too_early : string = "Too early"
let not_assessor : string = "Not assessor"
let assessor_already_exists : string = "Assessor already exists"
let cannot_remove_all_assessors : string = "Cannot remove all assessors"