
[@inline] let do_not_accept_tez : string = "Do not accept Tez"
[@inline] let owner_already_exist : string = "Owner already exists"
[@inline] let wrong_state : string = "Wrong state"
[@inline] let not_parent : string = "Not parent"
[@inline] let not_owner : string = "Not owner"
[@inline] let too_early : string = "Too early"
[@inline] let not_assessor : string = "Not assessor"
[@inline] let assessor_already_exists : string = "Assessor already exists"
[@inline] let cannot_remove_all_assessors : string = "Cannot remove all assessors"